name: CI

on:
  pull_request:

env:
  BUILDER_IMAGE: hstreamdb/logdevice-builder
  CLIENT_IMAGE: hstreamdb/logdevice-client
  SERVER_IMAGE: hstreamdb/logdevice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            _build
          key: ${{ runner.os }}-
          restore-keys: |
            ${{ runner.os }}-

      - name: prepare logdevice-builder
        run: |
          docker pull --tag $BUILDER_IMAGE || true
          docker build . -f docker/Dockerfile.builder --tag $BUILDER_IMAGE

      - name: Start a builder container
        run: docker run -td --name ld_builder --shm-size=500m -v $(pwd):/LogDevice -w /LogDevice $BUILDER_IMAGE bash

      # Note: do NOT use "Release" for CMAKE_BUILD_TYPE if you need run tests
      - name: build
        run: docker exec ld_builder bash -c 'mkdir -p _build && cd _build &&
          cmake -Dthriftpy3=OFF
            -DBUILD_SUBMODULES=OFF
            -DCMAKE_BUILD_TYPE=Debug
            -DBUILD_TESTS=ON
            -DCMAKE_MODULE_PATH=/usr/local/lib/cmake
            /LogDevice/logdevice/
          && make -j$(nproc) && make install -j$(nproc)
          '

      - name: tests
        run: docker exec ld_builder bash -c 'cd _build && ctest -j$(nproc) --output-on-failure -compress-output -T Test'
